// react-todo/src/components/Todos/TodoItem/index.jsx
import './style.scss';

const TodoItem = ({ todo, handleChangeTodo, handleDeleteTodo }) => {
  return (
    <li>
      <input type="checkbox" onChange={() => handleChangeTodo(todo)} checked={todo.isCompleted ? true : false} />
      <span className={todo.isCompleted ? 'is-completed' : null}>{todo.title}</span>
      <button onClick={() => handleDeleteTodo(todo.id)}>Del</button>
    </li>
  );
}

export default TodoItem;

// vue-todo/src/components/Todos/TodoItem/index.vue
<template>
  <li>
    <input
      type="checkbox"
      v-bind:checked="todo.isCompleted ? true : false"
      @change="toggleIsCompleted"
    />
    <span v-bind:class="todo.isCompleted && 'is-completed'">
      {{ todo.title }}
    </span>
    <button @click="$emit('delete-todo', todo.id)">Del</button>
  </li>
</template>

<script>
import { putTodoToDB } from "../../../services";

export default {
  name: "TodoItem",
  props: ["todo"],
  methods: {
    toggleIsCompleted() {
      const newTodo = {
        ...this.todo,
        isCompleted: !this.todo.isCompleted,
      };
      putTodoToDB(newTodo)
        .then((res) => {
          this.todo.isCompleted = res.isCompleted;
        })
        .catch((err) => console.log(err));
    },
  },
};
</script>

<style scoped lang='scss' src='./style.scss'>
</style>
