// vue-todo/src/components/AddTodo/index.vue
<template>
  <form @submit="handleSubmit">
    <input type="text" v-model="newTodoTitle" placeholder="Add Todo..." />
    <button type="submit">Add</button>
  </form>
</template>

<script>
import { v4 as uuidv4 } from "uuid";

export default {
  name: "AddTodo",
  data() {
    return {
      newTodoTitle: "",
    };
  },
  methods: {
    handleSubmit(e) {
      e.preventDefault();
      const newTodo = {
        id: uuidv4(),
        title: this.newTodoTitle,
        isCompleted: false,
      };
      this.$emit("add-todo", newTodo);
      this.newTodoTitle = "";
    },
  },
};
</script>

<style>
</style>

// angular-todo/src/app/components/add-todo/add-todo.component.ts
import { Component, OnInit, EventEmitter, Output } from '@angular/core';
import { v4 as uuidv4 } from 'uuid';

@Component({
  selector: 'app-add-todo',
  templateUrl: './add-todo.component.html',
  styleUrls: ['./add-todo.component.scss']
})
export class AddTodoComponent implements OnInit {
  @Output() addTodo: EventEmitter<any> = new EventEmitter();

  title: string = '';

  constructor() { }

  ngOnInit(): void {
  }

  onSubmit() {
    const todo = {
      id: uuidv4(),
      title: this.title,
      isCompleted: false
    }
    this.addTodo.emit(todo);
    this.title = '';
  }
}

<form (ngSubmit)="onSubmit()">
  <input type="text" name="title" [(ngModel)]="title" placeholder="Add Todo...">
  <button type="submit">Add</button>
</form>
