// react-todo/src/components/AddTodo/index.jsx
import { useState } from 'react';
import { v4 as uuidv4 } from 'uuid';

const AddTodo = ({ handleAddTodo }) => {
  const [newTodoTitle, setNewTodoTitle] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    const newTodo = {
      id: uuidv4(),
      title: newTodoTitle,
      isCompleted: false
    }
    handleAddTodo(newTodo);
    setNewTodoTitle('')
  }

  return (
    <form onSubmit={handleSubmit}>
      <input type="text" value={newTodoTitle} onChange={(e) => setNewTodoTitle(e.target.value)} placeholder='Add Todo...' />
      <button type='submit'>Add</button>
    </form>
  );
}

export default AddTodo;

// vue-todo/src/components/AddTodo/index.vue
<template>
  <form @submit="handleSubmit">
    <input type="text" v-model="newTodoTitle" placeholder="Add Todo..." />
    <button type="submit">Add</button>
  </form>
</template>

<script>
import { v4 as uuidv4 } from "uuid";

export default {
  name: "AddTodo",
  data() {
    return {
      newTodoTitle: "",
    };
  },
  methods: {
    handleSubmit(e) {
      e.preventDefault();
      const newTodo = {
        id: uuidv4(),
        title: this.newTodoTitle,
        isCompleted: false,
      };
      this.$emit("add-todo", newTodo);
      this.newTodoTitle = "";
    },
  },
};
</script>

<style>
</style>
