// vue-todo/src/views/About/index.vue
<template>
  <main class="about">
    <h1>About</h1>
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum cumque vel
      quibusdam accusantium modi quam ex eos soluta. Eligendi, culpa?
    </p>
  </main>
</template>

<script>
export default {
  name: "About",
};
</script>

<style lang='scss' src='./style.scss'>
</style>

// react-todo/src/pages/About/index.jsx
import './style.scss';

const About = () => {
  return (
    <main className='about'>
      <h1>About</h1>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi voluptas ab, eius similique quos laboriosam alias consequatur repellat. Voluptatum, voluptate.</p>
    </main>
  );
}

export default About;
