// vue-todo/src/views/Home/index.vue
<template>
  <main class="home">
    <AddTodo v-on:add-todo="addTodo" />
    <Todos v-bind:todos="todos" v-on:delete-todo="deleteTodo" />
  </main>
</template>

<script>
import { Todos, AddTodo } from "../../components";
import { getTodosFromDB, postTodoToDB, deleteTodoFromDB } from "../../services";

export default {
  name: "Home",
  components: {
    Todos,
    AddTodo,
  },
  data() {
    return {
      todos: [],
    };
  },
  methods: {
    addTodo(newTodo) {
      postTodoToDB(newTodo)
        .then((res) => {
          this.todos = [...this.todos, res];
        })
        .catch((err) => console.log(err));
    },
    deleteTodo(todoId) {
      deleteTodoFromDB(todoId)
        .then(() => {
          this.todos = this.todos.filter((elem) => elem.id !== todoId);
        })
        .catch((err) => {
          console.log(err);
        });
    },
  },
  created() {
    getTodosFromDB()
      .then((res) => {
        this.todos = res;
      })
      .catch((err) => console.log(err));
  },
};
</script>

<style lang='scss' src='./style.scss'>
</style>

// angular-todo/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Todo } from 'src/app/models/Todo';
import { TodoService } from 'src/app/services/todo.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
  todos: Todo[] = [];

  constructor(private todoService: TodoService) { }

  ngOnInit(): void {
    this.todoService.getTodosFromDB().subscribe(todos => {
      this.todos = todos
    })
  }

  deleteTodo(todo: Todo) {
    this.todoService.deleteTodoFromDB(todo).subscribe(() => {
      this.todos = this.todos.filter(elem => elem.id !== todo.id);
    });
  }

  addTodo(todo: Todo) {
    this.todoService.postTodoToDB(todo).subscribe(elem => {
      this.todos = [...this.todos, elem]
    })
  }
}

<main class="home">
  <app-add-todo (addTodo)='addTodo($event)'></app-add-todo>
  <app-todos [todos]='todos' (deleteTodo)='deleteTodo($event)'></app-todos>
</main>
