// vue-todo/src/views/Home/index.vue
<template>
  <main class="home">
    <AddTodo v-on:add-todo="addTodo" />
    <Todos v-bind:todos="todos" v-on:delete-todo="deleteTodo" />
  </main>
</template>

<script>
import { Todos, AddTodo } from "../../components";
import { getTodosFromDB, postTodoToDB, deleteTodoFromDB } from "../../services";

export default {
  name: "Home",
  components: {
    Todos,
    AddTodo,
  },
  data() {
    return {
      todos: [],
    };
  },
  methods: {
    addTodo(newTodo) {
      postTodoToDB(newTodo)
        .then((res) => {
          this.todos = [...this.todos, res];
        })
        .catch((err) => console.log(err));
    },
    deleteTodo(todoId) {
      deleteTodoFromDB(todoId)
        .then(() => {
          this.todos = this.todos.filter((elem) => elem.id !== todoId);
        })
        .catch((err) => {
          console.log(err);
        });
    },
  },
  created() {
    getTodosFromDB()
      .then((res) => {
        this.todos = res;
      })
      .catch((err) => console.log(err));
  },
};
</script>

<style lang='scss' src='./style.scss'>
</style>

// react-todo/src/pages/Home/index.jsx
import './style.scss';
import { useEffect, useState } from 'react';
import { AddTodo, Todos } from '../../components';
import { getTodosFromDB, postTodoToDB, deleteTodoFromDB, patchTodoToDB } from '../../services';

const Home = () => {
  const [todos, setTodos] = useState([]);

  useEffect(() => {
    getTodosFromDB()
      .then(res => {
        setTodos(res)
      })
  }, [])

  const handleAddTodo = (todo) => {
    postTodoToDB(todo)
      .then(res => {
        const newTodos = [...todos, res];
        setTodos(newTodos)
      })
  }

  const handleChangeTodo = (todo) => {
    const todoPart = { isCompleted: !todo.isCompleted }
    patchTodoToDB(todo.id, todoPart)
      .then(res => {
        const newTodos = [...todos].map(elem => {
          if (elem.id === todo.id) {
            return res
          }
          return elem
        })
        setTodos(newTodos)
      })
  }

  const handleDeleteTodo = (todoId) => {
    deleteTodoFromDB(todoId)
      .then(() => {
        const newTodos = [...todos].filter(elem => elem.id !== todoId)
        setTodos(newTodos)
      })
  }

  return (
    <main className='home'>
      <AddTodo handleAddTodo={handleAddTodo} />
      <Todos todos={todos} handleChangeTodo={handleChangeTodo} handleDeleteTodo={handleDeleteTodo} />
    </main>
  );
}

export default Home;
