// vue-todo/src/components/Todos/index.vue
<template>
  <div>
    <ul v-bind:key="todo.id" v-for="todo in todos">
      <TodoItem
        v-bind:todo="todo"
        v-on:delete-todo="$emit('delete-todo', todo.id)"
      />
    </ul>
  </div>
</template>

<script>
import TodoItem from "./TodoItem";

export default {
  name: "Todos",
  props: ["todos"],
  components: {
    TodoItem,
  },
};
</script>

<style>
</style>

// react-todo/src/components/Todos/index.jsx
import TodoItem from './TodoItem';

const Todos = ({ todos, handleChangeTodo, handleDeleteTodo }) => {
  return (
    <ul>
      {todos.map(todo => (
        <TodoItem key={todo.id} todo={todo} handleChangeTodo={handleChangeTodo} handleDeleteTodo={handleDeleteTodo} />
      ))}
    </ul>
  );
}

export default Todos;
