// vue-todo/src/components/Todos/TodoItem/index.vue
<template>
  <li>
    <input
      type="checkbox"
      v-bind:checked="todo.isCompleted ? true : false"
      @change="toggleIsCompleted"
    />
    <span v-bind:class="todo.isCompleted && 'is-completed'">
      {{ todo.title }}
    </span>
    <button @click="$emit('delete-todo', todo.id)">Del</button>
  </li>
</template>

<script>
import { putTodoToDB } from "../../../services";

export default {
  name: "TodoItem",
  props: ["todo"],
  methods: {
    toggleIsCompleted() {
      const newTodo = {
        ...this.todo,
        isCompleted: !this.todo.isCompleted,
      };
      putTodoToDB(newTodo)
        .then((res) => {
          this.todo.isCompleted = res.isCompleted;
        })
        .catch((err) => console.log(err));
    },
  },
};
</script>

<style scoped lang='scss' src='./style.scss'>
</style>

// angular-todo/src/app/components/todos/todo-item/todo-item.component.ts
import { Component, OnInit, Input, EventEmitter, Output } from '@angular/core';
import { Todo } from 'src/app/models/Todo';
import { TodoService } from '../../../services/todo.service';

@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.scss']
})
export class TodoItemComponent implements OnInit {
  @Input() todo!: Todo;
  @Output() deleteTodo: EventEmitter<Todo> = new EventEmitter();

  constructor(private todoService: TodoService) { }

  ngOnInit(): void {
  }

  // Set classes dynamically
  setClasses() {
    return {
      'is-completed': this.todo.isCompleted
    }
  }

  setChecked() {
    return this.todo.isCompleted
  }

  onToggle(todo: Todo) {
    const newTodo = {
      ...todo,
      isCompleted: !todo.isCompleted
    }
    this.todoService.putTodoToDB(newTodo).subscribe(todo => {
      this.todo = todo
    })
  }

  onDelete(todo: Todo) {
    this.deleteTodo.emit(todo)
  }
}

<li>
  <input (change)='onToggle(todo)' type="checkbox" [checked]='setChecked()'>
  <span [ngClass]='setClasses()'>{{todo.title}}</span>
  <button (click)='onDelete(todo)'>Del</button>
</li>
